### ISSUE TITLE
HA Config error

### ISSUE THREAD

**Issue by feradelectronics** [Breina/ha-artnet-led#9]
Artnet installs correctly but i get the following error when adding configuration.  I have even deleted all references to output_correction.  

ERROR:
Logger: homeassistant.loader
Source: custom_components/artnet_led/light.py:72
Integration: artnet_led ([documentation](https://github.com/Breina/ha-artnet-led), [issues](https://github.com/Breina/ha-artnet-led/issues))
First occurred: 6:15:58 AM (2 occurrences)
Last logged: 6:15:59 AM

Unexpected exception importing platform custom_components.artnet_led.light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/artnet_led/light.py", line 72, in <module>
    AVAILABLE_CORRECTIONS["quadratic"] = pyartnet.output_correction.quadratic
AttributeError: module 'pyartnet' has no attribute 'output_correction'

CONFIG (I USED):
### DMX-LIGHTS ###
light:
- platform: artnet_led
  host: 10.255.255.255
  max_fps: 25                           # Max 40 per second
  refresh_every: 0                      # Resend values if no fades are running every x seconds, 0 disables automatic refresh
  universes:                            # Support for multiple universes
    0:                                  # Nr of Universe (see configuration of your Art-Net Node)
#      output_correction: quadratic      # optional: output correction for the whole universe, will be used as default if nothing is set for the channel
      devices:
        # Dimmer
        - channel: 1                    # first channel of dmx dimmer
          name: my_dimmer               # name
          type: dimmer                  # type
          transition: 1                 # default duration of fades in sec. Will be overridden by Transition sent from HA

**Comment by Breina** [comment]
Please upgrade to version v0.0.6 to see if that solves the problem. I've upped the required pyartnet library version.

**Comment by feradelectronics** [comment]
Getting the following error with V0.0.6 updated.

Error while setting up artnet_led platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/artnet_led/light.py", line 170, in async_setup_platform
    await migrate_old_unique_ids(config, hass, host)
  File "/config/custom_components/artnet_led/light.py", line 189, in migrate_old_unique_ids
    if '/' in entity.unique_id:
AttributeError: 'NoneType' object has no attribute 'unique_id'

**Comment by Breina** [comment]
Alright thanks for the quick feedback, this edge case I didn't see in my testing.

This should be fixed in v0.0.7 for you.

**Comment by feradelectronics** [comment]
Thanks in advance for the quick updates

Getting another error:
Source: custom_components/artnet_led/light.py:170
Integration: artnet_led ([documentation](https://github.com/Breina/ha-artnet-led), [issues](https://github.com/Breina/ha-artnet-led/issues))
First occurred: 5:56:40 AM (1 occurrences)
Last logged: 5:56:40 AM

Could not find entity with entity ID light.my_dimmer

**Comment by Breina** [comment]
That should normally just be a warning now, not an error. The integration should work normally now and you shouldn't see this warning on subsequent reboots.

**Comment by feradelectronics** [comment]
Yes it is a warning now.  After reboots the warning still shows up in the log.

Now I am having problems connecting to my art-net to dmx interface.  Not sure what is causing this.  Will let you know how it works after some troubleshooting.

**Comment by feradelectronics** [comment]
DMX used to work with jnimmo dmx HA integration.  Not sure why it is not working now.  Using uDMX usb to DMX converter.  
If you have any suggestions to resolve this, it would be greatly appreciated.  Thanks in advance.

**Comment by Breina** [comment]
Are you using KiNet by any chance?

**Comment by feradelectronics** [comment]
No.  I am using art-net to DMX on my PC.  I am open to other suggestions.  I just know this worked in the past with jnimmo branch until recently.

**Comment by Breina** [comment]
Gonna mention #10 in here, as your problems seem related. Having a look between the diff of jnimmo and the pyartnet lib implementations.

**Comment by Breina** [comment]
If you are able to run python code directly, can you please help me test over here: https://github.com/Breina/ha-artnet-led/issues/10#issuecomment-1252100842 ?

**Comment by feradelectronics** [comment]
updated to v0.0.8 Still not able to connect to dmx.

error:
Logger: root
Source: custom_components/artnet_led/light.py:173
Integration: artnet_led ([documentation](https://github.com/Breina/ha-artnet-led), [issues](https://github.com/Breina/ha-artnet-led/issues))
First occurred: September 24, 2022 at 11:07:34 PM (7 occurrences)
Last logged: September 24, 2022 at 11:07:34 PM

Could not find entity with entity ID light.theatre...

**Comment by feradelectronics** [comment]
i can allow you to connect to my computer remotely if needed

**Comment by Breina** [comment]
Alright let's do it, please give email me the details to connect to you: info@breina.be

**Comment by Breina** [comment]
Also meanwhile, can you install 'The ArtNetominator' on your PC? That will help debugging your situation as well.

**Comment by cristianm** [comment]
Same issue that in #1252100842. With the ArtNetominator works but if try to use with the controller that currently works with the old addon, with this don´t.

**Comment by cristianm** [comment]
> i can allow you to connect to my computer remotely if needed

Same offer here.

**Comment by Breina** [comment]
@cristianm Do you also use a broadcast IP? Broadcasting isn't supported for sending DMX frames.

**Comment by cristianm** [comment]
I use the IP of the device. Is a Wifi to DMX device.

**Comment by Breina** [comment]
Closing this issue, as OP's issue turned out to be networking related. cristianm's is continued over at #10
